/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        if (args.length > 0) {
            System.out.println("你好，" + args[0] + "！");
        } else {
            System.out.println("你好，世界！");
        }
    }
}
